FROM dolphin-cpu-builder:latest

COPY . /workspace
WORKDIR /workspace

RUN rm -rf build && mkdir build
WORKDIR /workspace/build
RUN cmake -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_CUDA=OFF \
          -DFFTW_PATH="/usr/local/fftw3/lib" \
          .. && \
    cmake --build . -- -j$(nproc) && \
    cmake --install .

WORKDIR /workspace
RUN cmake -B /workspace/cli-build -S /workspace/frontends/cli \
      -DCMAKE_BUILD_TYPE=Release && \
    cmake --build /workspace/cli-build -- -j$(nproc)
